development:
  adapter: postgresql
  encoding: unicode
  database: coolcuttingboard_development
  pool: 5
  username: ace
  password: ace
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: coolcuttingboard_test
  pool: 5
  username: ace
  password: ace
  host: localhost